"""add organization_id to courses

Revision ID: 69cf87e9b323
Revises: 49a172b6873d
Create Date: 2026-10-08 12:52:49.343419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cf87e9b323'
down_revision: Union[str, Sequence[str], None] = '49a172b6873d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'organization_id')
    # ### end Alembic commands ###
