"""fix assessment_attempts duration column

Revision ID: 8d29472f29bc
Revises: a393e8c2e6e7
Create Date: 2026-08-17 17:20:44.369484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d29472f29bc'
down_revision: Union[str, Sequence[str], None] = 'a393e8c2e6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_attempts', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.drop_column('assessment_attempts', 'time_taken_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_attempts', sa.Column('time_taken_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('assessment_attempts', 'duration_seconds')
    # ### end Alembic commands ###
