"""add timing to responses and attempts

Revision ID: a393e8c2e6e7
Revises: ad47c79ced5f
Create Date: 2026-08-17 15:05:22.858343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a393e8c2e6e7'
down_revision: Union[str, Sequence[str], None] = 'ad47c79ced5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_attempts', sa.Column('time_taken_seconds', sa.Float(), nullable=True))
    op.add_column('responses', sa.Column('time_taken_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'time_taken_seconds')
    op.drop_column('assessment_attempts', 'time_taken_seconds')
    # ### end Alembic commands ###
