"""add soft delete to users, courses, assessments

Revision ID: d463d1c290fe
Revises: 6fdaf097ea6a
Create Date: 2026-08-13 15:44:12.096387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd463d1c290fe'
down_revision: Union[str, Sequence[str], None] = '6fdaf097ea6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('courses', 'deleted_at')
    op.drop_column('assessments', 'deleted_at')
    # ### end Alembic commands ###
